services:
  image-compare-srv:
    build:
      context: .
    image: h-alice/vismatch-svc  # Image name for the built service
    container_name: vismatch-svc
    env_file:
      - .env # Load environment variables from the .env file
    restart: unless-stopped
    volumes:
      - ./image_root:/app/image_root
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
    container_name: vismatch-frontend
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - image-compare-srv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      